builds:
  - binary: spurctx
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: spurctx
    homepage: "https://github.com/spurintel/spurctx-cli"
    repository:
      owner: spurintel
      name: homebrew-spurintel
    commit_author:
      name:  jjunqueira
      email: josh@spur.us

checksum:
  name_template: 'checksums.txt'
